const KUMPULAN_FLASHCARDS = [
  // === RANGKA: CRANIUM (TULANG KEPALA) ===
  { "kategori": "rangka", "sub": "Cranium", "tanya": "Tulang Dahi", "jawab": "Os Frontale" },
  { "kategori": "rangka", "sub": "Cranium", "tanya": "Tulang Ubun-ubun", "jawab": "Os Parietale" },
  { "kategori": "rangka", "sub": "Cranium", "tanya": "Tulang Kepala Belakang", "jawab": "Os Occipitale" },
  { "kategori": "rangka", "sub": "Cranium", "tanya": "Tulang Pelipis", "jawab": "Os Temporale" },
  { "kategori": "rangka", "sub": "Cranium", "tanya": "Tulang Baji", "jawab": "Os Sphenoidale" },
  { "kategori": "rangka", "sub": "Cranium", "tanya": "Tulang Tapis", "jawab": "Os Ethmoidale" },
  
  // === RANGKA: OSSA FACIEI (WAJAH) ===
  { "kategori": "rangka", "sub": "Ossa Faciei", "tanya": "Tulang Rahang Atas", "jawab": "Os Maxilla" },
  { "kategori": "rangka", "sub": "Ossa Faciei", "tanya": "Tulang Rahang Bawah", "jawab": "Os Mandibula" },
  { "kategori": "rangka", "sub": "Ossa Faciei", "tanya": "Tulang Pipi", "jawab": "Os Zygomaticum" },
  { "kategori": "rangka", "sub": "Ossa Faciei", "tanya": "Tulang Hidung", "jawab": "Os Nasale" },
  { "kategori": "rangka", "sub": "Ossa Faciei", "tanya": "Tulang Air Mata", "jawab": "Os Lacrimale" },
  { "kategori": "rangka", "sub": "Ossa Faciei", "tanya": "Tulang Langit-langit Mulut", "jawab": "Os Palatum" },
  { "kategori": "rangka", "sub": "Ossa Faciei", "tanya": "Tulang Sekat Rongga Hidung", "jawab": "Os Vomer" },

  // === RANGKA: COLUMNA VERTEBRALIS (TULANG BELAKANG) ===
  { "kategori": "rangka", "sub": "Columna Vertebralis", "tanya": "Tulang Leher Ruas Ke-1", "jawab": "Os Atlas" },
  { "kategori": "rangka", "sub": "Columna Vertebralis", "tanya": "Tulang Leher Ruas Ke-2", "jawab": "Os Axis" },
  { "kategori": "rangka", "sub": "Columna Vertebralis", "tanya": "7 Ruas Tulang Leher", "jawab": "Vertebrae Cervicales" },
  { "kategori": "rangka", "sub": "Columna Vertebralis", "tanya": "12 Ruas Tulang Punggung", "jawab": "Vertebrae Thoracales" },
  { "kategori": "rangka", "sub": "Columna Vertebralis", "tanya": "5 Ruas Tulang Pinggang", "jawab": "Vertebrae Lumbales" },
  { "kategori": "rangka", "sub": "Columna Vertebralis", "tanya": "Tulang Kelangkang", "jawab": "Os Sacrum" },
  { "kategori": "rangka", "sub": "Columna Vertebralis", "tanya": "Tulang Ekor", "jawab": "Os Coccygis" },

  // === RANGKA: TORAKS & GELANG BAHU ===
  { "kategori": "rangka", "sub": "Toraks", "tanya": "Tulang Dada", "jawab": "Os Sternum" },
  { "kategori": "rangka", "sub": "Toraks", "tanya": "Bagian Atas Tulang Dada (Hulu)", "jawab": "Manubrium Sterni" },
  { "kategori": "rangka", "sub": "Toraks", "tanya": "Bagian Tengah Tulang Dada (Badan)", "jawab": "Corpus Sterni" },
  { "kategori": "rangka", "sub": "Toraks", "tanya": "Taju Pedang Tulang Dada", "jawab": "Processus Xiphoideus" },
  { "kategori": "rangka", "sub": "Toraks", "tanya": "Tulang Rusuk Sejati", "jawab": "Os Costae Verae" },
  { "kategori": "rangka", "sub": "Toraks", "tanya": "Tulang Rusuk Palsu", "jawab": "Os Costae Spuriae" },
  { "kategori": "rangka", "sub": "Toraks", "tanya": "Tulang Rusuk Melayang", "jawab": "Os Costae Fluctuantes" },
  { "kategori": "rangka", "sub": "Gelang Bahu", "tanya": "Tulang Selangka", "jawab": "Os Clavicula" },
  { "kategori": "rangka", "sub": "Gelang Bahu", "tanya": "Tulang Belikat", "jawab": "Os Scapula" },

  // === RANGKA: EXTREMITAS SUPERIOR (LENGAN) ===
  { "kategori": "rangka", "sub": "Extremitas Superior", "tanya": "Tulang Lengan Atas", "jawab": "Os Humerus" },
  { "kategori": "rangka", "sub": "Extremitas Superior", "tanya": "Tulang Pengumpil (Searah Jempol)", "jawab": "Os Radius" },
  { "kategori": "rangka", "sub": "Extremitas Superior", "tanya": "Tulang Hasta (Searah Kelingking)", "jawab": "Os Ulna" },
  { "kategori": "rangka", "sub": "Extremitas Superior", "tanya": "Tulang Pergelangan Tangan", "jawab": "Os Carpal" },
  { "kategori": "rangka", "sub": "Extremitas Superior", "tanya": "Tulang Telapak Tangan", "jawab": "Os Metacarpal" },
  { "kategori": "rangka", "sub": "Extremitas Superior", "tanya": "Tulang Jari Tangan", "jawab": "Phalanges Digitorum Manus" },

  // === RANGKA: GELANG PANGGUL & EXTREMITAS INFERIOR (KENTAL/KAKI) ===
  { "kategori": "rangka", "sub": "Gelang Panggul", "tanya": "Tulang Usus", "jawab": "Os Ilium" },
  { "kategori": "rangka", "sub": "Gelang Panggul", "tanya": "Tulang Duduk", "jawab": "Os Ischium" },
  { "kategori": "rangka", "sub": "Gelang Panggul", "tanya": "Tulang Kemaluan", "jawab": "Os Pubis" },
  { "kategori": "rangka", "sub": "Extremitas Inferior", "tanya": "Tulang Paha", "jawab": "Os Femur" },
  { "kategori": "rangka", "sub": "Extremitas Inferior", "tanya": "Tulang Tempurung Lutut", "jawab": "Os Patella" },
  { "kategori": "rangka", "sub": "Extremitas Inferior", "tanya": "Tulang Kering (Besar)", "jawab": "Os Tibia" },
  { "kategori": "rangka", "sub": "Extremitas Inferior", "tanya": "Tulang Betis (Kecil)", "jawab": "Os Fibula" },
  { "kategori": "rangka", "sub": "Extremitas Inferior", "tanya": "Tulang Pergelangan Kaki", "jawab": "Os Tarsal" },
  { "kategori": "rangka", "sub": "Extremitas Inferior", "tanya": "Tulang Tumit Kaki", "jawab": "Os Calcaneus" },
  { "kategori": "rangka", "sub": "Extremitas Inferior", "tanya": "Tulang Telapak Kaki", "jawab": "Os Metatarsal" },
  { "kategori": "rangka", "sub": "Extremitas Inferior", "tanya": "Tulang Jari Kaki", "jawab": "Phalanges Digitorum Pedis" },

  // === PENCERNAAN ===
  { "kategori": "pencernaan", "sub": "Cavum Oris", "tanya": "Rongga Mulut", "jawab": "Cavum Oris" },
  { "kategori": "pencernaan", "sub": "Lingua", "tanya": "Lidah", "jawab": "Lingua / Glossa" },
  { "kategori": "pencernaan", "sub": "Glandula", "tanya": "Kelenjar Ludah Parotis (Dekat Telinga)", "jawab": "Glandula Parotis" },
  { "kategori": "pencernaan", "sub": "Glandula", "tanya": "Kelenjar Ludah Bawah Rahang", "jawab": "Glandula Submandibularis" },
  { "kategori": "pencernaan", "sub": "Glandula", "tanya": "Kelenjar Ludah Bawah Lidah", "jawab": "Glandula Sublingualis" },
  { "kategori": "pencernaan", "sub": "Canalis", "tanya": "Kerongkongan", "jawab": "Esofagus" },
  { "kategori": "pencernaan", "sub": "Gaster", "tanya": "Lambung", "jawab": "Gaster / Ventrikulus" },
  { "kategori": "pencernaan", "sub": "Gaster", "tanya": "Bagian Atas Lambung yang Bulat", "jawab": "Fundus Ventriculi" },
  { "kategori": "pencernaan", "sub": "Gaster", "tanya": "Katup Pembatas Esophagus dan Lambung", "jawab": "Sfingter Kardia" },
  { "kategori": "pencernaan", "sub": "Gaster", "tanya": "Katup Pembatas Lambung dan Usus Halus", "jawab": "Sfingter Pilorus" },
  { "kategori": "pencernaan", "sub": "Intestinum Tenue", "tanya": "Usus Dua Belas Jari", "jawab": "Duodenum" },
  { "kategori": "pencernaan", "sub": "Intestinum Tenue", "tanya": "Usus Kosong (Tengah)", "jawab": "Jejunum" },
  { "kategori": "pencernaan", "sub": "Intestinum Tenue", "tanya": "Usus Penyerapan (Akhir)", "jawab": "Ileum" },
  { "kategori": "pencernaan", "sub": "Intestinum Crassum", "tanya": "Usus Buntu / Kantung Awal Usus Besar", "jawab": "Secum" },
  { "kategori": "pencernaan", "sub": "Intestinum Crassum", "tanya": "Umbai Cacing", "jawab": "Appendix Vermiformis" },
  { "kategori": "pencernaan", "sub": "Intestinum Crassum", "tanya": "Usus Besar Naik", "jawab": "Colon Ascendens" },
  { "kategori": "pencernaan", "sub": "Intestinum Crassum", "tanya": "Usus Besar Mendatar", "jawab": "Colon Transversum" },
  { "kategori": "pencernaan", "sub": "Intestinum Crassum", "tanya": "Usus Besar Menurun", "jawab": "Colon Descendens" },
  { "kategori": "pencernaan", "sub": "Intestinum Crassum", "tanya": "Usus Besar Berbentuk S", "jawab": "Colon Sigmoideum" },
  { "kategori": "pencernaan", "sub": "Organ Aksesori", "tanya": "Hati", "jawab": "Hepar" },
  { "kategori": "pencernaan", "sub": "Organ Aksesori", "tanya": "Kandung Empedu", "jawab": "Vesica Fellea" },
  { "kategori": "pencernaan", "sub": "Organ Aksesori", "tanya": "Pankreas", "jawab": "Pankreas" },
  { "kategori": "pencernaan", "sub": "Jalur Akhir", "tanya": "Poros Usus / Tempat Simpan Feses", "jawab": "Rektum" },
  { "kategori": "pencernaan", "sub": "Jalur Akhir", "tanya": "Lubang Pelepasan Akhir", "jawab": "Anus" },

  // === KARDIOVASKULAR ===
  { "kategori": "kardio", "sub": "Jantung", "tanya": "Organ Jantung", "jawab": "Cor / Kardia" },
  { "kategori": "kardio", "sub": "Lapisan", "tanya": "Selaput Luar Jantung", "jawab": "Perikardium" },
  { "kategori": "kardio", "sub": "Lapisan", "tanya": "Lapisan Otot Jantung", "jawab": "Miokardium" },
  { "kategori": "kardio", "sub": "Lapisan", "tanya": "Lapisan Dalam Jantung", "jawab": "Endokardium" },
  { "kategori": "kardio", "sub": "Cavum Cor", "tanya": "Serambi Kanan", "jawab": "Atrium Dextra" },
  { "kategori": "kardio", "sub": "Cavum Cor", "tanya": "Serambi Kiri", "jawab": "Atrium Sinistra" },
  { "kategori": "kardio", "sub": "Cavum Cor", "tanya": "Bilik Kanan", "jawab": "Ventrikel Dextra" },
  { "kategori": "kardio", "sub": "Cavum Cor", "tanya": "Bilik Kiri", "jawab": "Ventrikel Sinistra" },
  { "kategori": "kardio", "sub": "Valvula", "tanya": "Katup Jantung Kanan (Tiga Daun)", "jawab": "Valvula Trikuspidalis" },
  { "kategori": "kardio", "sub": "Valvula", "tanya": "Katup Jantung Kiri (Dua Daun/Mitral)", "jawab": "Valvula Bikuspidalis" },
  { "kategori": "kardio", "sub": "Valvula", "tanya": "Katup Antara Bilik Kanan & Arteri Pulmonalis", "jawab": "Valvula Semilunaris Pulmonal" },
  { "kategori": "kardio", "sub": "Valvula", "tanya": "Katup Antara Bilik Kiri & Aorta", "jawab": "Valvula Semilunaris Aorta" },
  { "kategori": "kardio", "sub": "Vasa Sanguinea", "tanya": "Pembuluh Darah Arteri Terbesar", "jawab": "Aorta" },
  { "kategori": "kardio", "sub": "Vasa Sanguinea", "tanya": "Vena Besar Tubuh Bagian Atas", "jawab": "Vena Cava Superior" },
  { "kategori": "kardio", "sub": "Vasa Sanguinea", "tanya": "Vena Besar Tubuh Bagian Bawah", "jawab": "Vena Cava Inferior" },
  { "kategori": "kardio", "sub": "Vasa Sanguinea", "tanya": "Arteri Menuju Paru-paru", "jawab": "Arteri Pulmonalis" },
  { "kategori": "kardio", "sub": "Vasa Sanguinea", "tanya": "Vena dari Paru-paru Menuju Jantung", "jawab": "Vena Pulmonalis" },
  { "kategori": "kardio", "sub": "Vasa Sanguinea", "tanya": "Arteri Khusus Penyuplai Nutrisi Otot Jantung", "jawab": "Arteri Koronaria" },

  // === RESPIRASI ===
  { "kategori": "respirasi", "sub": "Jalur Atas", "tanya": "Rongga Hidung", "jawab": "Cavum Nasalis" },
  { "kategori": "respirasi", "sub": "Jalur Atas", "tanya": "Sekat Hidung Tengah", "jawab": "Septum Nasi" },
  { "kategori": "respirasi", "sub": "Jalur Atas", "tanya": "Tenggorokan (Pertigaan Jalur)", "jawab": "Faring" },
  { "kategori": "respirasi", "sub": "Jalur Atas", "tanya": "Pangkal Tenggorokan (Kotak Suara)", "jawab": "Laring" },
  { "kategori": "respirasi", "sub": "Jalur Atas", "tanya": "Katup Tulang Rawan Penutup Jalur Napas", "jawab": "Epiglotis" },
  { "kategori": "respirasi", "sub": "Jalur Utama", "tanya": "Batang Tenggorokan", "jawab": "Trakea" },
  { "kategori": "respirasi", "sub": "Jalur Utama", "tanya": "Cabang Utama Trakea Kanan & Kiri", "jawab": "Bronkus" },
  { "kategori": "respirasi", "sub": "Jalur Utama", "tanya": "Cabang-cabang Kecil di Dalam Paru", "jawab": "Bronkiolus" },
  { "kategori": "respirasi", "sub": "Pulmo", "tanya": "Organ Paru-paru", "jawab": "Pulmo" },
  { "kategori": "respirasi", "sub": "Pulmo", "tanya": "Kantung Udara Tempat Pertukaran Gas", "jawab": "Alveolus" },
  { "kategori": "respirasi", "sub": "Pulmo", "tanya": "Selaput Pembungkus Paru-paru", "jawab": "Pleura" },
  { "kategori": "respirasi", "sub": "Musculus", "tanya": "Otot Utama Pembatas Rongga Dada & Perut", "jawab": "Diafragma" },

  // === PERSARAFAN ===
  { "kategori": "saraf", "sub": "Encephalon", "tanya": "Otak Besar", "jawab": "Cerebrum" },
  { "kategori": "saraf", "sub": "Encephalon", "tanya": "Otak Kecil (Keseimbangan)", "jawab": "Cerebellum" },
  { "kategori": "saraf", "sub": "Encephalon", "tanya": "Batang Otak", "jawab": "Brainstem" },
  { "kategori": "saraf", "sub": "Encephalon", "tanya": "Otak Tengah", "jawab": "Mesencephalon" },
  { "kategori": "saraf", "sub": "Encephalon", "tanya": "Jembatan Varol (Penyambung Otak)", "jawab": "Pons Varolii" },
  { "kategori": "saraf", "sub": "Encephalon", "tanya": "Sumsum Lanjutan (Pusat Napas & Jantung)", "jawab": "Medulla Oblongata" },
  { "kategori": "saraf", "sub": "Systema Centrale", "tanya": "Sumsum Tulang Belakang", "jawab": "Medulla Spinalis" },
  { "kategori": "saraf", "sub": "Meninges", "tanya": "Selaput Otak Terluar (Keras)", "jawab": "Dura Mater" },
  { "kategori": "saraf", "sub": "Meninges", "tanya": "Selaput Otak Tengah (Sarang Laba-laba)", "jawab": "Arachnoid Mater" },
  { "kategori": "saraf", "sub": "Meninges", "tanya": "Selaput Otak Terdalam (Lembut/Tipis)", "jawab": "Pia Mater" },
  { "kategori": "saraf", "sub": "Cellula", "tanya": "Sel Saraf", "jawab": "Neuron" },

  // === URINARIA ===
  { "kategori": "urinaria", "sub": "Ren", "tanya": "Organ Ginjal", "jawab": "Ren / Nephros" },
  { "kategori": "urinaria", "sub": "Ren", "tanya": "Korteks Ginjal", "jawab": "Cortex Renis" },
  { "kategori": "urinaria", "sub": "Ren", "tanya": "Medula Ginjal (Sumsum Ginjal)", "jawab": "Medulla Renis" },
  { "kategori": "urinaria", "sub": "Ren", "tanya": "Piala Ginjal / Rongga Ginjal", "jawab": "Pelvis Renis" },
  { "kategori": "urinaria", "sub": "Cellula", "tanya": "Satuan Fungsional Penyaring Ginjal", "jawab": "Nefron" },
  { "kategori": "urinaria", "sub": "Canalis", "tanya": "Saluran dari Ginjal ke Kandung Kemih", "jawab": "Ureter" },
  { "kategori": "urinaria", "sub": "Canalis", "tanya": "Kantung Penampung Urin Sementara", "jawab": "Vesica Urinaria" },
  { "kategori": "urinaria", "sub": "Canalis", "tanya": "Saluran Pembuangan Urin Keluar Tubuh", "jawab": "Uretra" },

  // === INTEGUMEN ===
  { "kategori": "integumen", "sub": "Cutis", "tanya": "Lapisan Kulit Terluar (Tanpa Pembuluh Darah)", "jawab": "Epidermis" },
  { "kategori": "integumen", "sub": "Cutis", "tanya": "Lapisan Kulit Jangat (Banyak Saraf & Darah)", "jawab": "Dermis" },
  { "kategori": "integumen", "sub": "Cutis", "tanya": "Lapisan Lemak Bawah Kulit", "jawab": "Subkutan / Hipodermis" },
  { "kategori": "integumen", "sub": "Glandula", "tanya": "Kelenjar Keringat", "jawab": "Glandula Sudorifera" },
  { "kategori": "integumen", "sub": "Glandula", "tanya": "Kelenjar Minyak Kulit", "jawab": "Glandula Sebacea" },
  { "kategori": "integumen", "sub": "Pilus", "tanya": "Otot Penegak Rambut Kulit (Merinding)", "jawab": "Musculus Arrector Pili" },

  // === OTOT (MUSKULAR) ===
  { "kategori": "otot", "sub": "Jenis Otot", "tanya": "Otot Melekat Rangka Kerja Sadar", "jawab": "Otot Lurik (Musculus Striatus)" },
  { "kategori": "otot", "sub": "Jenis Otot", "tanya": "Otot Dinding Organ Dalam Kerja Tidak Sadar", "jawab": "Otot Polos (Musculus Nonstriatus)" },
  { "kategori": "otot", "sub": "Jenis Otot", "tanya": "Otot Dinding Jantung", "jawab": "Otot Jantung (Myokardium)" },
  { "kategori": "otot", "sub": "Regio Kepala", "tanya": "Otot Pengunyah Utama Rahang", "jawab": "Musculus Masseter" },
  { "kategori": "otot", "sub": "Regio Kepala", "tanya": "Otot Dahi Pengangkat Alis", "jawab": "Musculus Frontalis" },
  { "kategori": "otot", "sub": "Regio Kepala", "tanya": "Otot Melingkar Penutup Mata", "jawab": "Musculus Orbicularis Oculi" },
  { "kategori": "otot", "sub": "Regio Leher", "tanya": "Otot Leher Besar Pemutar Kepala", "jawab": "Musculus Sternocleidomastoideus" },
  { "kategori": "otot", "sub": "Regio Dada", "tanya": "Otot Dada Besar", "jawab": "Musculus Pectoralis Major" },
  { "kategori": "otot", "sub": "Regio Bahu", "tanya": "Otot Segitiga Bahu (Lokasi Suntik IM)", "jawab": "Musculus Deltoideus" },
  { "kategori": "otot", "sub": "Lengan Atas", "tanya": "Otot Lengan Depan Penekuk Siku", "jawab": "Musculus Biceps Brachii" },
  { "kategori": "otot", "sub": "Lengan Atas", "tanya": "Otot Lengan Belakang Meluruskan Siku", "jawab": "Musculus Triceps Brachii" },
  { "kategori": "otot", "sub": "Regio Perut", "tanya": "Otot Perut Lurus Depan (Sixpack)", "jawab": "Musculus Rectus Abdominis" },
  { "kategori": "otot", "sub": "Tungkai Atas", "tanya": "Otot Bokong Terbesar", "jawab": "Musculus Gluteus Maximus" },
  { "kategori": "otot", "sub": "Tungkai Atas", "tanya": "Otot Terpanjang Tubuh Melintasi Paha", "jawab": "Musculus Sartorius" },
  { "kategori": "otot", "sub": "Tungkai Bawah", "tanya": "Otot Betis Besar Belakang", "jawab": "Musculus Gastrocnemius" },

  // === ENDOKRIN ===
  { "kategori": "endokrin", "sub": "Glandula Utama", "tanya": "Kelenjar 'Master of Gland' Dasar Otak", "jawab": "Glandula Pituitari (Hipofisis)" },
  { "kategori": "endokrin", "sub": "Glandula Utama", "tanya": "Kelenjar Kupu-kupu Leher Depan", "jawab": "Glandula Thyroidea" },
  { "kategori": "endokrin", "sub": "Glandula Utama", "tanya": "4 Kelenjar Kecil Belakang Tiroid", "jawab": "Glandula Parathyroidea" },
  { "kategori": "endokrin", "sub": "Glandula Utama", "tanya": "Kelenjar Anak Ginjal Penghasil Adrenalin", "jawab": "Glandula Suprarenalis (Adrenal)" },
  { "kategori": "endokrin", "sub": "Glandula Utama", "tanya": "Kelenjar Biji Pinus Otak Penghasil Melatonin", "jawab": "Glandula Pinealis" },
  { "kategori": "endokrin", "sub": "Glandula Utama", "tanya": "Kelenjar Belakang Tulang Dada Pembentuk Sel T", "jawab": "Glandula Thymus" },
  { "kategori": "endokrin", "sub": "Pankreas", "tanya": "Pusat Kelenjar Endokrin Pankreas", "jawab": "Pulau-pulau Langerhans" },
  { "kategori": "endokrin", "sub": "Hormon Pankreas", "tanya": "Hormon Penukur Gula Darah", "jawab": "Insulin (Sel Beta)" },
  { "kategori": "endokrin", "sub": "Hormon Pankreas", "tanya": "Hormon Peningkat Gula Darah", "jawab": "Glukagon (Sel Alfa)" },
  { "kategori": "endokrin", "sub": "Hormon Reproduksi", "tanya": "Hormon Utama Maskulin Laki-laki", "jawab": "Testosteron" },
  { "kategori": "endokrin", "sub": "Hormon Reproduksi", "tanya": "Hormon Utama Siklus Wanita", "jawab": "Estrogen & Progesteron" },
  { "kategori": "endokrin", "sub": "Hormon Hipofisis", "tanya": "Hormon Pemicu Kontraksi Rahim Melahirkan", "jawab": "Oksitosin" }
];